name: full_learn_flutter
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

#Google
  url_launcher: ^6.3.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  image_picker: ^1.1.2
  
#animation
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.2

#context
  kartal: ^4.0.4

#service
  dio: ^5.5.0+1
  vexana: ^4.1.0

#cache
  shared_preferences: ^2.3.1
  flutter_secure_storage: ^9.2.2
#Core
  equatable: ^2.0.5
  collection: any

#states
  provider: ^6.1.2
  flutter_mobx: ^2.2.1+1
  mobx_codegen: ^2.6.1
  flutter_bloc: ^8.1.6

#localization
  easy_localization: ^3.0.7
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  mockito: ^5.4.4


flutter:


  uses-material-design: true

  assets:
    
    - assets/apple-and-book-png-transparent-apple-and-book-images-274565.png
    - assets/png/
    - assets/lottie/
    - assets/translations/
